/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author juans
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        Grupo2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbtnHashMod = new javax.swing.JRadioButton();
        rbtnCuadrado = new javax.swing.JRadioButton();
        rbtnPlegamiento = new javax.swing.JRadioButton();
        rbtnTruncamiento = new javax.swing.JRadioButton();
        rbtnSecuencial = new javax.swing.JRadioButton();
        rbtnBinaria = new javax.swing.JRadioButton();
        textElemento = new javax.swing.JLabel();
        textArray = new javax.swing.JLabel();
        cajaElemento = new javax.swing.JTextField();
        cajaArray = new javax.swing.JTextField();
        btnDinamico = new javax.swing.JButton();
        jCambiador = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fondoPlaca = new javax.swing.JLabel();
        imagenesRango = new javax.swing.JLabel();
        direc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECCIONE EL TIPO DE BUSQUEDA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        Grupo1.add(rbtnHashMod);
        rbtnHashMod.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        rbtnHashMod.setForeground(new java.awt.Color(255, 255, 255));
        rbtnHashMod.setText("Hash Mod");
        rbtnHashMod.setContentAreaFilled(false);
        rbtnHashMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnHashModActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnHashMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 20));

        Grupo1.add(rbtnCuadrado);
        rbtnCuadrado.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        rbtnCuadrado.setForeground(new java.awt.Color(255, 255, 255));
        rbtnCuadrado.setText("Hash Cuadrado");
        rbtnCuadrado.setContentAreaFilled(false);
        jPanel1.add(rbtnCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 160, 20));

        Grupo1.add(rbtnPlegamiento);
        rbtnPlegamiento.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        rbtnPlegamiento.setForeground(new java.awt.Color(255, 255, 255));
        rbtnPlegamiento.setText("Hash Plegamiento");
        rbtnPlegamiento.setContentAreaFilled(false);
        rbtnPlegamiento.setFocusPainted(false);
        rbtnPlegamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPlegamientoActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnPlegamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 190, 20));

        Grupo1.add(rbtnTruncamiento);
        rbtnTruncamiento.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        rbtnTruncamiento.setForeground(new java.awt.Color(255, 255, 255));
        rbtnTruncamiento.setText("Hash Truncamiento");
        rbtnTruncamiento.setContentAreaFilled(false);
        jPanel1.add(rbtnTruncamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 180, -1));

        Grupo1.add(rbtnSecuencial);
        rbtnSecuencial.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSecuencial.setText("Secuencial");
        rbtnSecuencial.setContentAreaFilled(false);
        jPanel1.add(rbtnSecuencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 160, 20));

        Grupo1.add(rbtnBinaria);
        rbtnBinaria.setForeground(new java.awt.Color(255, 255, 255));
        rbtnBinaria.setText("Binaria");
        rbtnBinaria.setContentAreaFilled(false);
        jPanel1.add(rbtnBinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, -1));

        textElemento.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        textElemento.setForeground(new java.awt.Color(255, 255, 255));
        textElemento.setText("Elemento:");
        jPanel1.add(textElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        textArray.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        textArray.setForeground(new java.awt.Color(255, 255, 255));
        textArray.setText("Cantidad de Claves:");
        jPanel1.add(textArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
        jPanel1.add(cajaElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 210, -1));

        cajaArray.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(cajaArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 160, 20));

        btnDinamico.setText("CREAR");
        jPanel1.add(btnDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        jCambiador.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jCambiador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crear", "Agregar", "Buscar", "Eliminar" }));
        jCambiador.setToolTipText("");
        jPanel1.add(jCambiador, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 60, 20));

        btnLimpiar.setText("LIMPIAR");
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Crear, Agregar, Buscar o Eliminar?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 8)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(226, 169, 226));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("By Brayan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 340, 590));

        fondoPlaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/placa.png"))); // NOI18N
        getContentPane().add(fondoPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 340, 580));
        getContentPane().add(imagenesRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, -1));

        direc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DIREC.png"))); // NOI18N
        getContentPane().add(direc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, 450));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/texto.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        fondo.setLabelFor(jPanel1);
        fondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fondo.setRequestFocusEnabled(false);
        fondo.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        fondo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void rbtnHashModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnHashModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnHashModActionPerformed

    private void rbtnPlegamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPlegamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnPlegamientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup Grupo1;
    public javax.swing.ButtonGroup Grupo2;
    public javax.swing.JButton btnDinamico;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JTextField cajaArray;
    public javax.swing.JTextField cajaElemento;
    public javax.swing.JLabel direc;
    private javax.swing.JLabel fondo;
    public javax.swing.JLabel fondoPlaca;
    public javax.swing.JLabel imagenesRango;
    public javax.swing.JComboBox<String> jCambiador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton rbtnBinaria;
    public javax.swing.JRadioButton rbtnCuadrado;
    public javax.swing.JRadioButton rbtnHashMod;
    public javax.swing.JRadioButton rbtnPlegamiento;
    public javax.swing.JRadioButton rbtnSecuencial;
    public javax.swing.JRadioButton rbtnTruncamiento;
    public javax.swing.JLabel textArray;
    public javax.swing.JLabel textElemento;
    // End of variables declaration//GEN-END:variables

    public void blanquearCampos() {
        cajaElemento.setText("");
        cajaArray.setText("");
    }
    
    public void mostrarMensajes(String cadena){
        
        JOptionPane.showMessageDialog(null, cadena, "ERROR" , JOptionPane.WARNING_MESSAGE);
    }

    public void mostrarImagenes(String referencia) {

        URL urlImagen = getClass().getResource(referencia);

        ImageIcon icono = new ImageIcon(urlImagen);
        imagenesRango.setIcon(icono);

    }
  
    
    
    

}
