/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author Brayan
 */
public class Information extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Information.class.getName());
    
    int xMouse, yMouse;
    
    private static Information instance;
    
    public static Information getInstance() {
        if (instance == null) {
            instance = new Information();
        }
        return instance;
    }

    /**
     * Creates new form Information
     */
    public Information() {
        setNimbusLookAndFeel();
        initComponents();
    }
    
    private void setNimbusLookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        aceptarLabel = new javax.swing.JLabel();
        dragPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(18, 18, 18));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(672, 412));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(672, 412));
        setSize(new java.awt.Dimension(672, 412));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backGround.setBackground(new java.awt.Color(18, 18, 18));
        backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 102));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTextPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px; margin: 40px; line-height: 1.6;'> Esta aplicación pretende implementar los temas desarrollados en<br> el curso de Ciencias de la computación II, como lo son las búsquedas internas, externas, árboles, etc. Creado por Brayan Aguirre</body> </html>");
        jTextPane1.setFocusable(false);
        jTextPane1.setOpaque(false);
        jScrollPane2.setViewportView(jTextPane1);

        backGround.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 500, 260));

        aceptarLabel.setFont(new java.awt.Font("Cambria Math", 0, 48)); // NOI18N
        aceptarLabel.setForeground(new java.awt.Color(255, 255, 255));
        aceptarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aceptarLabel.setText("Aceptar");
        aceptarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aceptarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aceptarLabelMouseExited(evt);
            }
        });
        backGround.add(aceptarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 210, 50));

        dragPanel.setBackground(new java.awt.Color(18, 18, 18));
        dragPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        dragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragPanelMouseDragged(evt);
            }
        });
        dragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout dragPanelLayout = new javax.swing.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        backGround.add(dragPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 30));

        getContentPane().add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 672, 412));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarLabelMouseEntered
        aceptarLabel.setForeground(new Color(124, 212, 187));
    }//GEN-LAST:event_aceptarLabelMouseEntered

    private void aceptarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarLabelMouseExited
        aceptarLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_aceptarLabelMouseExited

    private void aceptarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarLabelMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_aceptarLabelMouseClicked

    private void dragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragPanelMouseDragged

    private void dragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMousePressed
       xMouse = evt.getX();
       yMouse = evt.getY();
    }//GEN-LAST:event_dragPanelMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aceptarLabel;
    private javax.swing.JPanel backGround;
    private javax.swing.JPanel dragPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
