/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author Brayan
 */
public class PrincipalPage extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    
    private static PrincipalPage instance;
    
    public static PrincipalPage getInstance() {
        if (instance == null) {
            instance = new PrincipalPage();
        }
        return instance;
    }
    
    public PrincipalPage() {
        setNimbusLookAndFeel();
        initComponents();
        dinamicoTxt.setVisible(false);
        dinamicoTxt1.setVisible(false);
    }
  
    private void setNimbusLookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        cardPanel = new javax.swing.JPanel();
        busquedasInternas = new javax.swing.JPanel();
        binarySearchbtn = new javax.swing.JPanel();
        binarySearchLabel = new javax.swing.JLabel();
        linealSearchbtn = new javax.swing.JPanel();
        linealSearchLabel = new javax.swing.JLabel();
        hModSearchbtn = new javax.swing.JPanel();
        hModSearchLabel = new javax.swing.JLabel();
        hSquareSearchbtn = new javax.swing.JPanel();
        hSquareSearchLabel = new javax.swing.JLabel();
        hFoldingSearchbtn = new javax.swing.JPanel();
        hFoldingSearchLabel = new javax.swing.JLabel();
        htTruncationSearchbtn = new javax.swing.JPanel();
        hTruncationSearchLabel = new javax.swing.JLabel();
        tituloPaginaTxt = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JLabel();
        dinamicoTxt = new javax.swing.JLabel();
        busquedasArboles = new javax.swing.JPanel();
        residualTreeBtn = new javax.swing.JPanel();
        residualTreeLabel = new javax.swing.JLabel();
        digitalTreeBtn = new javax.swing.JPanel();
        digitalTreeLabel = new javax.swing.JLabel();
        multipleTreeBtn = new javax.swing.JPanel();
        multipleTreeLabel = new javax.swing.JLabel();
        huffmanTreeBtn = new javax.swing.JPanel();
        huffmanTreeLabel = new javax.swing.JLabel();
        tituloPaginaTxt1 = new javax.swing.JLabel();
        btnVolver1 = new javax.swing.JLabel();
        btnSiguiente1 = new javax.swing.JLabel();
        dinamicoTxt1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        deco2 = new javax.swing.JLabel();
        dragPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        bienvenidaTxt = new javax.swing.JLabel();
        deco1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hash&Seek");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        principalPanel.setBackground(new java.awt.Color(255, 255, 255));
        principalPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        principalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardPanel.setBackground(new java.awt.Color(30, 30, 30));
        cardPanel.setLayout(new java.awt.CardLayout());

        busquedasInternas.setBackground(new java.awt.Color(102, 153, 255));

        binarySearchbtn.setBackground(new java.awt.Color(51, 51, 51));

        binarySearchLabel.setBackground(new java.awt.Color(102, 102, 102));
        binarySearchLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        binarySearchLabel.setForeground(new java.awt.Color(255, 255, 255));
        binarySearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        binarySearchLabel.setText("Busqueda Binaria");
        binarySearchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        binarySearchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                binarySearchLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                binarySearchLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                binarySearchLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout binarySearchbtnLayout = new javax.swing.GroupLayout(binarySearchbtn);
        binarySearchbtn.setLayout(binarySearchbtnLayout);
        binarySearchbtnLayout.setHorizontalGroup(
            binarySearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(binarySearchLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        binarySearchbtnLayout.setVerticalGroup(
            binarySearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, binarySearchbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(binarySearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        linealSearchbtn.setBackground(new java.awt.Color(51, 51, 51));

        linealSearchLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        linealSearchLabel.setForeground(new java.awt.Color(255, 255, 255));
        linealSearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linealSearchLabel.setText("Busqueda Lineal");
        linealSearchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linealSearchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linealSearchLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linealSearchLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linealSearchLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout linealSearchbtnLayout = new javax.swing.GroupLayout(linealSearchbtn);
        linealSearchbtn.setLayout(linealSearchbtnLayout);
        linealSearchbtnLayout.setHorizontalGroup(
            linealSearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linealSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        linealSearchbtnLayout.setVerticalGroup(
            linealSearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linealSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        hModSearchbtn.setBackground(new java.awt.Color(60, 60, 60));

        hModSearchLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hModSearchLabel.setForeground(new java.awt.Color(255, 255, 255));
        hModSearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hModSearchLabel.setText("Hash Mod");
        hModSearchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hModSearchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hModSearchLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hModSearchLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hModSearchLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hModSearchbtnLayout = new javax.swing.GroupLayout(hModSearchbtn);
        hModSearchbtn.setLayout(hModSearchbtnLayout);
        hModSearchbtnLayout.setHorizontalGroup(
            hModSearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hModSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        hModSearchbtnLayout.setVerticalGroup(
            hModSearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hModSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        hSquareSearchbtn.setBackground(new java.awt.Color(51, 51, 51));

        hSquareSearchLabel.setBackground(new java.awt.Color(51, 51, 51));
        hSquareSearchLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hSquareSearchLabel.setForeground(new java.awt.Color(255, 255, 255));
        hSquareSearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hSquareSearchLabel.setText("Hash Cuadrado");
        hSquareSearchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hSquareSearchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hSquareSearchLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hSquareSearchLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hSquareSearchLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hSquareSearchbtnLayout = new javax.swing.GroupLayout(hSquareSearchbtn);
        hSquareSearchbtn.setLayout(hSquareSearchbtnLayout);
        hSquareSearchbtnLayout.setHorizontalGroup(
            hSquareSearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hSquareSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        hSquareSearchbtnLayout.setVerticalGroup(
            hSquareSearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hSquareSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        hFoldingSearchbtn.setBackground(new java.awt.Color(60, 60, 60));

        hFoldingSearchLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hFoldingSearchLabel.setForeground(new java.awt.Color(255, 255, 255));
        hFoldingSearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hFoldingSearchLabel.setText("Hash Plegamiento");
        hFoldingSearchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hFoldingSearchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hFoldingSearchLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hFoldingSearchLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hFoldingSearchLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hFoldingSearchbtnLayout = new javax.swing.GroupLayout(hFoldingSearchbtn);
        hFoldingSearchbtn.setLayout(hFoldingSearchbtnLayout);
        hFoldingSearchbtnLayout.setHorizontalGroup(
            hFoldingSearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hFoldingSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        hFoldingSearchbtnLayout.setVerticalGroup(
            hFoldingSearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hFoldingSearchbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hFoldingSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        htTruncationSearchbtn.setBackground(new java.awt.Color(60, 60, 60));

        hTruncationSearchLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hTruncationSearchLabel.setForeground(new java.awt.Color(255, 255, 255));
        hTruncationSearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hTruncationSearchLabel.setText("Hash Truncamiento");
        hTruncationSearchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hTruncationSearchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hTruncationSearchLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hTruncationSearchLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hTruncationSearchLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout htTruncationSearchbtnLayout = new javax.swing.GroupLayout(htTruncationSearchbtn);
        htTruncationSearchbtn.setLayout(htTruncationSearchbtnLayout);
        htTruncationSearchbtnLayout.setHorizontalGroup(
            htTruncationSearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hTruncationSearchLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        htTruncationSearchbtnLayout.setVerticalGroup(
            htTruncationSearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, htTruncationSearchbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hTruncationSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tituloPaginaTxt.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        tituloPaginaTxt.setForeground(new java.awt.Color(255, 255, 255));
        tituloPaginaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPaginaTxt.setText("Busquedas Internas");

        btnSiguiente.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSiguiente.setText("Siguiente >");
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseExited(evt);
            }
        });

        dinamicoTxt.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        dinamicoTxt.setForeground(new java.awt.Color(255, 255, 255));
        dinamicoTxt.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px; margin: 40px; line-height: 1.6;'> BIENVENIDOS <br> Este es un texto de prueba</body> </html>");

        javax.swing.GroupLayout busquedasInternasLayout = new javax.swing.GroupLayout(busquedasInternas);
        busquedasInternas.setLayout(busquedasInternasLayout);
        busquedasInternasLayout.setHorizontalGroup(
            busquedasInternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedasInternasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(busquedasInternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloPaginaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(busquedasInternasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(busquedasInternasLayout.createSequentialGroup()
                        .addComponent(dinamicoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(busquedasInternasLayout.createSequentialGroup()
                        .addGroup(busquedasInternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(linealSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(binarySearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hModSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(busquedasInternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hSquareSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hFoldingSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(htTruncationSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        busquedasInternasLayout.setVerticalGroup(
            busquedasInternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedasInternasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(tituloPaginaTxt)
                .addGap(12, 12, 12)
                .addGroup(busquedasInternasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(busquedasInternasLayout.createSequentialGroup()
                        .addComponent(linealSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(binarySearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(hModSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(busquedasInternasLayout.createSequentialGroup()
                        .addComponent(hSquareSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(hFoldingSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(htTruncationSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dinamicoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 150, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );

        cardPanel.add(busquedasInternas, "card3");

        busquedasArboles.setBackground(new java.awt.Color(102, 153, 255));

        residualTreeBtn.setBackground(new java.awt.Color(51, 51, 51));

        residualTreeLabel.setBackground(new java.awt.Color(102, 102, 102));
        residualTreeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        residualTreeLabel.setForeground(new java.awt.Color(255, 255, 255));
        residualTreeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        residualTreeLabel.setText("Arbol por Residuos");
        residualTreeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        residualTreeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                residualTreeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                residualTreeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                residualTreeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout residualTreeBtnLayout = new javax.swing.GroupLayout(residualTreeBtn);
        residualTreeBtn.setLayout(residualTreeBtnLayout);
        residualTreeBtnLayout.setHorizontalGroup(
            residualTreeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(residualTreeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        residualTreeBtnLayout.setVerticalGroup(
            residualTreeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, residualTreeBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(residualTreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        digitalTreeBtn.setBackground(new java.awt.Color(51, 51, 51));

        digitalTreeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        digitalTreeLabel.setForeground(new java.awt.Color(255, 255, 255));
        digitalTreeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        digitalTreeLabel.setText("Arboles Digitales");
        digitalTreeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        digitalTreeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                digitalTreeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                digitalTreeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                digitalTreeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout digitalTreeBtnLayout = new javax.swing.GroupLayout(digitalTreeBtn);
        digitalTreeBtn.setLayout(digitalTreeBtnLayout);
        digitalTreeBtnLayout.setHorizontalGroup(
            digitalTreeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(digitalTreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        digitalTreeBtnLayout.setVerticalGroup(
            digitalTreeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(digitalTreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        multipleTreeBtn.setBackground(new java.awt.Color(60, 60, 60));

        multipleTreeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        multipleTreeLabel.setForeground(new java.awt.Color(255, 255, 255));
        multipleTreeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multipleTreeLabel.setText("Residuos Multiples");
        multipleTreeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multipleTreeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multipleTreeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multipleTreeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multipleTreeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout multipleTreeBtnLayout = new javax.swing.GroupLayout(multipleTreeBtn);
        multipleTreeBtn.setLayout(multipleTreeBtnLayout);
        multipleTreeBtnLayout.setHorizontalGroup(
            multipleTreeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multipleTreeBtnLayout.createSequentialGroup()
                .addComponent(multipleTreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        multipleTreeBtnLayout.setVerticalGroup(
            multipleTreeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(multipleTreeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        huffmanTreeBtn.setBackground(new java.awt.Color(51, 51, 51));

        huffmanTreeLabel.setBackground(new java.awt.Color(51, 51, 51));
        huffmanTreeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        huffmanTreeLabel.setForeground(new java.awt.Color(255, 255, 255));
        huffmanTreeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        huffmanTreeLabel.setText("Arboles Huffman");
        huffmanTreeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        huffmanTreeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                huffmanTreeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                huffmanTreeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                huffmanTreeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout huffmanTreeBtnLayout = new javax.swing.GroupLayout(huffmanTreeBtn);
        huffmanTreeBtn.setLayout(huffmanTreeBtnLayout);
        huffmanTreeBtnLayout.setHorizontalGroup(
            huffmanTreeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(huffmanTreeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        huffmanTreeBtnLayout.setVerticalGroup(
            huffmanTreeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(huffmanTreeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tituloPaginaTxt1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        tituloPaginaTxt1.setForeground(new java.awt.Color(255, 255, 255));
        tituloPaginaTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPaginaTxt1.setText("Busquedas Internas - Arboles");

        btnVolver1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        btnVolver1.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver1.setText("< Volver");
        btnVolver1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolver1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolver1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolver1MouseExited(evt);
            }
        });

        btnSiguiente1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        btnSiguiente1.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSiguiente1.setText("Siguiente >");
        btnSiguiente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguiente1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSiguiente1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSiguiente1MouseExited(evt);
            }
        });

        dinamicoTxt1.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        dinamicoTxt1.setForeground(new java.awt.Color(255, 255, 255));
        dinamicoTxt1.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px; margin: 40px; line-height: 1.6;'> BIENVENIDOS <br> Este es un texto de prueba</body> </html>");
        dinamicoTxt1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout busquedasArbolesLayout = new javax.swing.GroupLayout(busquedasArboles);
        busquedasArboles.setLayout(busquedasArbolesLayout);
        busquedasArbolesLayout.setHorizontalGroup(
            busquedasArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedasArbolesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(busquedasArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloPaginaTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(busquedasArbolesLayout.createSequentialGroup()
                        .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(busquedasArbolesLayout.createSequentialGroup()
                        .addComponent(dinamicoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(busquedasArbolesLayout.createSequentialGroup()
                        .addGroup(busquedasArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(digitalTreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(residualTreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(busquedasArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(huffmanTreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multipleTreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        busquedasArbolesLayout.setVerticalGroup(
            busquedasArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busquedasArbolesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(tituloPaginaTxt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(busquedasArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(digitalTreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huffmanTreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(busquedasArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(residualTreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multipleTreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130)
                .addComponent(dinamicoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(busquedasArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente1))
                .addContainerGap())
        );

        cardPanel.add(busquedasArboles, "card3");

        principalPanel.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 520, 650));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Logo.png"))); // NOI18N
        principalPanel.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 460, 380));

        deco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Decoration2.png"))); // NOI18N
        deco2.setText("jLabel2");
        principalPanel.add(deco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, 0, 1010, 730));

        dragPanel.setBackground(new java.awt.Color(255, 255, 255));
        dragPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        dragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragPanelMouseDragged(evt);
            }
        });
        dragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragPanelMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        txtExit.setBackground(new java.awt.Color(255, 255, 255));
        txtExit.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout dragPanelLayout = new javax.swing.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dragPanelLayout.createSequentialGroup()
                .addContainerGap(1240, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dragPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        principalPanel.add(dragPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        version.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        version.setForeground(new java.awt.Color(0, 0, 0));
        version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        version.setText("Desarrollado por Brayan - v0.7.1-beta");
        principalPanel.add(version, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 700, 1280, -1));

        bienvenidaTxt.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        bienvenidaTxt.setForeground(new java.awt.Color(0, 0, 0));
        bienvenidaTxt.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px; margin: 40px; line-height: 1.6;'> BIENVENIDOS <br> Esta aplicación pretende implementar los temas desarrollados en<br> el curso de Ciencias de la computación II, como lo son las búsquedas internas, externas, árboles, etc.</body> </html>");
        principalPanel.add(bienvenidaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 680, 160));

        deco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Decoration2.png"))); // NOI18N
        principalPanel.add(deco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, 310, 1030));

        getContentPane().add(principalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1280, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragPanelMousePressed

    private void dragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragPanelMouseDragged

    private void linealSearchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linealSearchLabelMouseEntered
        linealSearchLabel.setForeground(new Color(124, 212, 187));
        dinamicoTxt.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px;"
                + " margin: 40px; line-height: 1.6;'> Busqueda Lineal <br> Es un tipo de busqueda que se encarga de buscar en una"
                + " estructura de manera secuencial, es decir, verificando direccion por direccion </body> </html>");
        dinamicoTxt.setVisible(true);
    }//GEN-LAST:event_linealSearchLabelMouseEntered

    private void linealSearchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linealSearchLabelMouseExited
         linealSearchLabel.setForeground(Color.WHITE);
         dinamicoTxt.setVisible(false);
    }//GEN-LAST:event_linealSearchLabelMouseExited

    private void linealSearchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linealSearchLabelMouseClicked
        this.setVisible(false);
        LinealSearch.getInstance().setVisible(true);
    }//GEN-LAST:event_linealSearchLabelMouseClicked

    private void binarySearchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binarySearchLabelMouseEntered
        binarySearchLabel.setForeground(new Color(124, 212, 187));
        dinamicoTxt.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px;"
                + " margin: 40px; line-height: 1.6;'> Busqueda Binaria <br> Es un tipo de busqueda que se encarga de buscar en una"
                + " estructura ordenada, dividiendo la estructura en partes iguales y comparando con la clave original</body> </html>");
        dinamicoTxt.setVisible(true);
    }//GEN-LAST:event_binarySearchLabelMouseEntered

    private void binarySearchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binarySearchLabelMouseExited
        binarySearchLabel.setForeground(Color.white);
        dinamicoTxt.setVisible(false);
    }//GEN-LAST:event_binarySearchLabelMouseExited

    private void binarySearchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binarySearchLabelMouseClicked
        this.setVisible(false);
        BinarySearch.getInstance().setVisible(true);
    }//GEN-LAST:event_binarySearchLabelMouseClicked

    private void hModSearchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hModSearchLabelMouseClicked
        this.setVisible(false);
        HModSearch.getInstance().setVisible(true);
    }//GEN-LAST:event_hModSearchLabelMouseClicked

    private void hModSearchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hModSearchLabelMouseEntered
        hModSearchLabel.setForeground(new Color(124, 212, 187));
        dinamicoTxt.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px;"
                + " margin: 40px; line-height: 1.6;'> Busqueda Hash Mod <br> Es un tipo de busqueda que se encarga de buscar en una"
                + " estructura utilizando la operación \"Modulo\" </body> </html>");
        dinamicoTxt.setVisible(true);
    }//GEN-LAST:event_hModSearchLabelMouseEntered

    private void hModSearchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hModSearchLabelMouseExited
        hModSearchLabel.setForeground(Color.white);
        dinamicoTxt.setVisible(false);
    }//GEN-LAST:event_hModSearchLabelMouseExited

    private void hSquareSearchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hSquareSearchLabelMouseClicked
        this.setVisible(false);
        HSquareSearch.getInstance().setVisible(true);
    }//GEN-LAST:event_hSquareSearchLabelMouseClicked

    private void hSquareSearchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hSquareSearchLabelMouseEntered
       hSquareSearchLabel.setForeground(new Color(124, 212, 187));
       dinamicoTxt.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px;"
                + " margin: 40px; line-height: 1.6;'> Busqueda Hash Medio Cuadrado <br> Es un tipo de busqueda que se encarga de buscar en una"
                + " estructura usando \"Hashes\" a partir del cuadrado de la clave original </body> </html>");
        dinamicoTxt.setVisible(true);
    }//GEN-LAST:event_hSquareSearchLabelMouseEntered

    private void hSquareSearchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hSquareSearchLabelMouseExited
        hSquareSearchLabel.setForeground(Color.white);
        dinamicoTxt.setVisible(false);
    }//GEN-LAST:event_hSquareSearchLabelMouseExited

    private void hFoldingSearchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hFoldingSearchLabelMouseClicked
        this.setVisible(false);
        HFoldingSearch.getInstance().setVisible(true);
    }//GEN-LAST:event_hFoldingSearchLabelMouseClicked

    private void hFoldingSearchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hFoldingSearchLabelMouseEntered
        hFoldingSearchLabel.setForeground(new Color(124, 212, 187));
        dinamicoTxt.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px;"
                + " margin: 40px; line-height: 1.6;'> Busqueda Hash Plegamiento <br> Es un tipo de busqueda que se encarga de buscar en una"
                + " estructura escogiendo ciertos digitos de la clave original para formar el \"Hash\" o \"dirección\" </body> </html>");
        dinamicoTxt.setVisible(true);
    }//GEN-LAST:event_hFoldingSearchLabelMouseEntered

    private void hFoldingSearchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hFoldingSearchLabelMouseExited
        hFoldingSearchLabel.setForeground(Color.white);
        dinamicoTxt.setVisible(false);
    }//GEN-LAST:event_hFoldingSearchLabelMouseExited

    private void hTruncationSearchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hTruncationSearchLabelMouseClicked
        this.setVisible(false);
        HTruncationSearch.getInstance().setVisible(true);
    }//GEN-LAST:event_hTruncationSearchLabelMouseClicked

    private void hTruncationSearchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hTruncationSearchLabelMouseEntered
        hTruncationSearchLabel.setForeground(new Color(124, 212, 187));
        dinamicoTxt.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px;"
                + " margin: 40px; line-height: 1.6;'> Busqueda Hash Truncamiento <br> Es un tipo de busqueda que se encarga de buscar en una"
                + " estructura separando la clave en partes iguales y aplicando una operacion aritmetica sobre estas partes </body> </html>");
        dinamicoTxt.setVisible(true);
    }//GEN-LAST:event_hTruncationSearchLabelMouseEntered

    private void hTruncationSearchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hTruncationSearchLabelMouseExited
        hTruncationSearchLabel.setForeground(Color.white);
        dinamicoTxt.setVisible(false);
    }//GEN-LAST:event_hTruncationSearchLabelMouseExited

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setBackground(Color.white);
    }//GEN-LAST:event_exitBtnMouseExited

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(Color.red);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void btnSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseEntered
        btnSiguiente.setForeground(new Color(124, 212, 187));
    }//GEN-LAST:event_btnSiguienteMouseEntered

    private void btnSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseExited
        btnSiguiente.setForeground(Color.white);
    }//GEN-LAST:event_btnSiguienteMouseExited

    private void residualTreeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_residualTreeLabelMouseClicked
        this.setVisible(false);
        ResidualTreeSearch.getInstance().setVisible(true);
    }//GEN-LAST:event_residualTreeLabelMouseClicked

    private void residualTreeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_residualTreeLabelMouseEntered
        residualTreeLabel.setForeground(new Color(124, 212, 187));
        dinamicoTxt1.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px;"
                + " margin: 40px; line-height: 1.6;'> Busqueda Por Residuos <br> Es un tipo de busqueda que se encarga de buscar en una"
                + " estructura de Arbol, dejando la raiz vacia y solucionando las posibles colisiones </body> </html>");
        dinamicoTxt1.setVisible(true);
    }//GEN-LAST:event_residualTreeLabelMouseEntered

    private void residualTreeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_residualTreeLabelMouseExited
        residualTreeLabel.setForeground(Color.white);
        dinamicoTxt1.setVisible(false);
        
    }//GEN-LAST:event_residualTreeLabelMouseExited

    private void digitalTreeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digitalTreeLabelMouseClicked
        this.setVisible(false);
        DigitalTreeSearch.getInstance().setVisible(true);
    }//GEN-LAST:event_digitalTreeLabelMouseClicked

    private void digitalTreeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digitalTreeLabelMouseEntered
        digitalTreeLabel.setForeground(new Color(124, 212, 187));
        dinamicoTxt1.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px;"
                + " margin: 40px; line-height: 1.6;'> Busqueda Por Arbol Digital <br> Es un tipo de busqueda que se encarga de buscar en una"
                + " estructura de arbol a partir del codigo binario a 5 bits de una clave previamente obtenida </body> </html>");
        dinamicoTxt1.setVisible(true);
    }//GEN-LAST:event_digitalTreeLabelMouseEntered

    private void digitalTreeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digitalTreeLabelMouseExited
        digitalTreeLabel.setForeground(Color.white);
        dinamicoTxt1.setVisible(false);
    }//GEN-LAST:event_digitalTreeLabelMouseExited

    private void multipleTreeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multipleTreeLabelMouseClicked
        this.setVisible(false);
        MultipleTreeSearch.getInstance().setVisible(true);
    }//GEN-LAST:event_multipleTreeLabelMouseClicked

    private void multipleTreeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multipleTreeLabelMouseEntered
        multipleTreeLabel.setForeground(new Color(124, 212, 187));
        dinamicoTxt1.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px;"
                + " margin: 40px; line-height: 1.6;'> Busqueda Por residuos Multiples <br> Es un tipo de busqueda que se encarga de buscar en una"
                + " estructura de arbol usando el binario de cada clave en grupos de 2 bits </body> </html>");
        dinamicoTxt1.setVisible(true);
    }//GEN-LAST:event_multipleTreeLabelMouseEntered

    private void multipleTreeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multipleTreeLabelMouseExited
        multipleTreeLabel.setForeground(Color.white);
        dinamicoTxt1.setVisible(false);
    }//GEN-LAST:event_multipleTreeLabelMouseExited

    private void huffmanTreeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_huffmanTreeLabelMouseClicked
        this.setVisible(false);
        HuffmanTreeSearch.getInstance().setVisible(true);
    }//GEN-LAST:event_huffmanTreeLabelMouseClicked

    private void huffmanTreeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_huffmanTreeLabelMouseEntered
        huffmanTreeLabel.setForeground(new Color(124, 212, 187));
        dinamicoTxt1.setText("<html> <body style='text-align: center; font-family: Segoe UI, Arial, sans-serif; font-size: 14px;"
                + " margin: 40px; line-height: 1.6;'> Busqueda Por Arboles de Huffman <br> Es un tipo de busqueda que se encarga de buscar en una"
                + " estructura de arbol a partir de las frecuencias de aparicion de las claves </body> </html>");
        dinamicoTxt1.setVisible(true);
    }//GEN-LAST:event_huffmanTreeLabelMouseEntered

    private void huffmanTreeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_huffmanTreeLabelMouseExited
        huffmanTreeLabel.setForeground(Color.white);
        dinamicoTxt1.setVisible(false);
    }//GEN-LAST:event_huffmanTreeLabelMouseExited

    private void btnVolver1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolver1MouseEntered
        btnVolver1.setForeground(new Color(124, 212, 187));
    }//GEN-LAST:event_btnVolver1MouseEntered

    private void btnVolver1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolver1MouseExited
        btnVolver1.setForeground(Color.white);
    }//GEN-LAST:event_btnVolver1MouseExited

    private void btnSiguiente1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguiente1MouseEntered
        btnSiguiente1.setForeground(new Color(124, 212, 187));
    }//GEN-LAST:event_btnSiguiente1MouseEntered

    private void btnSiguiente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguiente1MouseExited
        btnSiguiente1.setForeground(Color.white);
    }//GEN-LAST:event_btnSiguiente1MouseExited

    private void btnSiguiente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguiente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguiente1MouseClicked

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
         CardLayout cl = (CardLayout) cardPanel.getLayout();
         cl.next(cardPanel);
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void btnVolver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolver1MouseClicked
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.previous(cardPanel);
    }//GEN-LAST:event_btnVolver1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel bienvenidaTxt;
    private javax.swing.JLabel binarySearchLabel;
    private javax.swing.JPanel binarySearchbtn;
    private javax.swing.JLabel btnSiguiente;
    private javax.swing.JLabel btnSiguiente1;
    private javax.swing.JLabel btnVolver1;
    private javax.swing.JPanel busquedasArboles;
    private javax.swing.JPanel busquedasInternas;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel deco1;
    private javax.swing.JLabel deco2;
    private javax.swing.JPanel digitalTreeBtn;
    private javax.swing.JLabel digitalTreeLabel;
    private javax.swing.JLabel dinamicoTxt;
    private javax.swing.JLabel dinamicoTxt1;
    private javax.swing.JPanel dragPanel;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel hFoldingSearchLabel;
    private javax.swing.JPanel hFoldingSearchbtn;
    private javax.swing.JLabel hModSearchLabel;
    private javax.swing.JPanel hModSearchbtn;
    private javax.swing.JLabel hSquareSearchLabel;
    private javax.swing.JPanel hSquareSearchbtn;
    private javax.swing.JLabel hTruncationSearchLabel;
    private javax.swing.JPanel htTruncationSearchbtn;
    private javax.swing.JPanel huffmanTreeBtn;
    private javax.swing.JLabel huffmanTreeLabel;
    private javax.swing.JLabel linealSearchLabel;
    private javax.swing.JPanel linealSearchbtn;
    private javax.swing.JPanel multipleTreeBtn;
    private javax.swing.JLabel multipleTreeLabel;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JPanel residualTreeBtn;
    private javax.swing.JLabel residualTreeLabel;
    private javax.swing.JLabel tituloPaginaTxt;
    private javax.swing.JLabel tituloPaginaTxt1;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
