/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author Brayan
 */
public class PrincipalPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalPage.class.getName());

    int xMouse, yMouse;
    
    private static PrincipalPage instance;
    
    public static PrincipalPage getInstance() {
        if (instance == null) {
            instance = new PrincipalPage();
        }
        return instance;
    }
    
    public PrincipalPage() {
        setNimbusLookAndFeel();
        initComponents();
    }
  
    private void setNimbusLookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        background2 = new javax.swing.JPanel();
        linealSearchbtn = new javax.swing.JPanel();
        linealSearchLabel = new javax.swing.JLabel();
        binarySearchbtn = new javax.swing.JPanel();
        binarySearchLabel = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        txtWelcome = new javax.swing.JLabel();
        dragPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(18, 18, 18));
        background.setMinimumSize(new java.awt.Dimension(1280, 720));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background2.setBackground(new java.awt.Color(30, 30, 30));
        background2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linealSearchbtn.setBackground(new java.awt.Color(60, 60, 60));
        linealSearchbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linealSearchLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        linealSearchLabel.setForeground(new java.awt.Color(255, 255, 255));
        linealSearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linealSearchLabel.setText("Busqueda Lineal");
        linealSearchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linealSearchLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linealSearchLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linealSearchLabelMouseExited(evt);
            }
        });
        linealSearchbtn.add(linealSearchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        background2.add(linealSearchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 21, -1, 50));

        binarySearchbtn.setBackground(new java.awt.Color(60, 60, 60));

        binarySearchLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        binarySearchLabel.setForeground(new java.awt.Color(255, 255, 255));
        binarySearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        binarySearchLabel.setText("Busqueda Binaria");

        javax.swing.GroupLayout binarySearchbtnLayout = new javax.swing.GroupLayout(binarySearchbtn);
        binarySearchbtn.setLayout(binarySearchbtnLayout);
        binarySearchbtnLayout.setHorizontalGroup(
            binarySearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(binarySearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        binarySearchbtnLayout.setVerticalGroup(
            binarySearchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(binarySearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        background2.add(binarySearchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 50));

        background.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 470, 640));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Logo.png"))); // NOI18N
        background.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 460, 190));

        txtWelcome.setBackground(new java.awt.Color(255, 255, 255));
        txtWelcome.setFont(new java.awt.Font("Cambria Math", 0, 48)); // NOI18N
        txtWelcome.setForeground(new java.awt.Color(255, 255, 255));
        txtWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtWelcome.setText("Bienvenidos");
        txtWelcome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtWelcome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtWelcomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtWelcomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtWelcomeMouseExited(evt);
            }
        });
        background.add(txtWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 290, -1));

        dragPanel.setBackground(new java.awt.Color(18, 18, 18));
        dragPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        dragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragPanelMouseDragged(evt);
            }
        });
        dragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragPanelMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(30, 30, 30));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        txtExit.setBackground(new java.awt.Color(255, 255, 255));
        txtExit.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        txtExit.setForeground(new java.awt.Color(255, 255, 255));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout dragPanelLayout = new javax.swing.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dragPanelLayout.createSequentialGroup()
                .addContainerGap(1240, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dragPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(dragPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1280, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragPanelMousePressed

    private void dragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragPanelMouseDragged

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(Color.red);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setBackground(new Color(30, 30, 30));
    }//GEN-LAST:event_exitBtnMouseExited

    private void txtWelcomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWelcomeMouseEntered
        txtWelcome.setForeground(new Color(124, 212, 187));
    }//GEN-LAST:event_txtWelcomeMouseEntered

    private void txtWelcomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWelcomeMouseExited
        txtWelcome.setForeground(Color.white);
    }//GEN-LAST:event_txtWelcomeMouseExited

    private void txtWelcomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWelcomeMouseClicked
       Information.getInstance().setVisible(true);
    }//GEN-LAST:event_txtWelcomeMouseClicked

    private void linealSearchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linealSearchLabelMouseEntered
        linealSearchLabel.setForeground(new Color(124, 212, 187));
    }//GEN-LAST:event_linealSearchLabelMouseEntered

    private void linealSearchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linealSearchLabelMouseExited
         linealSearchLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_linealSearchLabelMouseExited

    private void linealSearchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linealSearchLabelMouseClicked
        this.setVisible(false);
        LinealSearch.getInstance().setVisible(true);
    }//GEN-LAST:event_linealSearchLabelMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel background;
    private javax.swing.JPanel background2;
    private javax.swing.JLabel binarySearchLabel;
    private javax.swing.JPanel binarySearchbtn;
    private javax.swing.JPanel dragPanel;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel linealSearchLabel;
    private javax.swing.JPanel linealSearchbtn;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
