/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author juans
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        cajaBuscador = new javax.swing.JTextField();
        jCambiador = new javax.swing.JComboBox<>();
        btnMostrar = new javax.swing.JButton();
        btnDinamico = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        TituloText = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaBuscador.setBackground(new java.awt.Color(255, 255, 255));
        cajaBuscador.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        cajaBuscador.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(cajaBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 810, 50));

        jCambiador.setBackground(new java.awt.Color(45, 45, 45));
        jCambiador.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jCambiador.setForeground(new java.awt.Color(255, 255, 255));
        jCambiador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar", "Buscar", "Eliminar" }));
        jCambiador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 130, 180), 2));
        jCambiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCambiadorActionPerformed(evt);
            }
        });
        getContentPane().add(jCambiador, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 40));

        btnMostrar.setBackground(new java.awt.Color(51, 51, 51));
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/MostrarButton.png"))); // NOI18N
        btnMostrar.setContentAreaFilled(false);
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 340, 60));

        btnDinamico.setBackground(new java.awt.Color(255, 255, 255));
        btnDinamico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/saveIcon.png"))); // NOI18N
        getContentPane().add(btnDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 310, 50, 50));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/SalirButton.png"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 200, 90));

        TituloText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Title.png"))); // NOI18N
        getContentPane().add(TituloText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.jpg"))); // NOI18N
        fondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fondo.setRequestFocusEnabled(false);
        fondo.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        fondo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jCambiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCambiadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCambiadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup Grupo1;
    private javax.swing.JLabel TituloText;
    public javax.swing.JButton btnDinamico;
    public javax.swing.JButton btnMostrar;
    public javax.swing.JButton btnSalir;
    public javax.swing.JTextField cajaBuscador;
    private javax.swing.JLabel fondo;
    public javax.swing.JComboBox<String> jCambiador;
    // End of variables declaration//GEN-END:variables

    public void blanquearCampos() {
        cajaBuscador.setText("");
    }

//    public void coloresBuscar(String op) {
//        if (op.equalsIgnoreCase("buscar")) {
//            cajaNombre.setBackground(new java.awt.Color(199, 199, 199));
//            cajaApellido.setBackground(new java.awt.Color(199, 199, 199));
//            cajaLibreta.setBackground(new java.awt.Color(199, 199, 199));
//            ((JTextFieldDateEditor) cajaFecha.getDateEditor())
//                    .setDisabledTextColor(Color.BLACK);
//        } else {
//            cajaNombre.setBackground(new java.awt.Color(255, 255, 255));
//            cajaApellido.setBackground(new java.awt.Color(255, 255, 255));
//            cajaLibreta.setBackground(new java.awt.Color(255, 255, 255));
//            cajaFecha.setBackground(new java.awt.Color(255, 255, 255));
//        }
//
//    }


    
    public void mostrarMensajes(String cadena){
        
        JOptionPane.showMessageDialog(null, cadena, "MENSAJE" , JOptionPane.INFORMATION_MESSAGE);
    }
    

    public void setImages(String referencia) {

        URL urlImagen = getClass().getResource(referencia);

        ImageIcon icono = new ImageIcon(urlImagen);
        btnDinamico.setIcon(icono);

    }
  
    
    
    

}
